language: node_js
install:
  - npm install package-json-validator
  - gem install mdl
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - yarn typecheck
  - yarn test --coverageDirectory=. --coverage
  - node_modules/package-json-validator/bin/pjv --filename=package.json
  - mdl README.md
after_script:
  - ./cc-test-reporter after-build --coverage-input-type=clover --exit-code $TRAVIS_TEST_RESULT
